# 服务端口
server:
  port: 3355

springcloudConfigClientVersion:
  test-version-1

spring:
  application:
    # 应用名称
    name: config-client-3355

#################################### Eureka 相关配置 ####################################
eureka:
  instance:
    # 设置 Eureka 注册中心上实例名称
    instance-id: config-3355
    # 支持显示服务 ip
    prefer-ip-address: true
  client:
    service-url:
      # 是否需要注册到 Eureka
      register-with-eureka: true
      fetch-registry: true
      # Eureka 集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka


